=== AllenInstitute/cell-feature-data/data-validation/schema/feature-def.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "featureDefSchema",
    "title": "Feature Defs",
    "description": "Measured features in the dataset",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "displayName": {
            "description": "Human readable name",
            "type": "string"
        },
        "description": {
            "description": "Description of how the data was collected/measured",
            "type": "string"
        },
        "tooltip": {
            "description": "Shorter version of description",
            "type": "string"
        },
        "unit": {
            "description": "unit of measurement",
            "type": "string"
        },
        "key": {
            "description": "Id of the feature",
            "type": "string"
        },
        "discrete": {
            "description": "Whether it's a continuous measurement or not",
            "type": "boolean"
        },
        "options": {
            "description": "For discrete features, display items for each value",
            "type": "object"
        }
    },
    "required": [
        "displayName",
        "description",
        "tooltip",
        "unit",
        "key",
        "discrete"
    ]
}

=== AllenInstitute/cell-feature-data/dataset-1-4-1/feature_defs.json
[
    {
        "key": "cellular-volume",
        "displayName": "Cellular Volume",
        "unit": "fL",
        "description": "The volume of a cell, as measured by segmented voxels and associated edge length, in units of femtoliter (fL)",
        "tooltip": "The volume of a cell, as measured by segmented voxels and associated edge length, in units of femtoliter (fL)",
        "discrete": false
    },
    {
        "displayName": "Cell surface area",
        "description": "The surface area of a cell, as measured by segmented pixels and associated edge length, in units of \u00b5m\u00b2.",
        "tooltip": "The surface area of a cell, as measured by segmented pixels and associated edge length, in units of \u00b5m\u00b2.",
        "unit": "\u00b5m\u00b2",
        "key": "cell-surface-area",
        "discrete": false
    },
    {
        "key": "nuclear-volume",
        "displayName": "Nuclear Volume",
        "unit": "fL",
        "description": "The volume of a nucleus of a given cell, as measured by segmented voxels and associated edge length, in units of femtoliter (fL).",
        "tooltip": "The volume of a nucleus of a given cell, as measured by segmented voxels and associated edge length, in units of femtoliter (fL).",
        "discrete": false
    },
    {
        "key": "nuclear-surface-area",
        "displayName": "Nuclear Surface Area",
        "unit": "\u00b5m\u00b2",
        "description": "The surface area of a nucleus of a given cell as measured by segmented pixels and associated edge length, in units of \u00b5m\u00b2.",
        "tooltip": "The surface area of a nucleus of a given cell as measured by segmented pixels and associated edge length, in units of \u00b5m\u00b2.",
        "discrete": false
    },
    {
        "displayName": "Anaphase segmentation complete",
        "description": "Whether the segmentation contains the entirety of the cell boundary (only determined for cells in anaphase).",
        "tooltip": "Whether the segmentation contains the entirety of the cell boundary (only determined for cells in anaphase).",
        "unit": "unitless",
        "key": "anaphase-segmentation-complete",
        "discrete": true,
        "options": {
            "0": {
                "color": "#fed98e",
                "name": "Incomplete"
            },
            "1": {
                "color": "#7f48f3",
                "name": "Complete"
            },
            "-1": {
                "color": "#838383",
                "name": "Not determined"
            }
        }
    },
    {
        "displayName": "Interphase or mitosis",
        "description": "Whether a particular cell is currently in interphase or mitosis.",
        "tooltip": "Whether a particular cell is currently in interphase or mitosis.",
        "unit": "stage",
        "key": "interphase-or-mitosis",
        "discrete": true,
        "options": {
            "0": {
                "color": "#fed98e",
                "name": "Incomplete"
            },
            "1": {
                "color": "#7f48f3",
                "name": "Complete"
            },
            "-1": {
                "color": "#838383",
                "name": "Not determined"
            }
        }
    },
    {
        "displayName": "Interphase & mitotic stages",
        "description": "Which of our 5 stages of the cell cycle (determined by the shape of the DNA) a particular cell is currently in.",
        "tooltip": "Which of our 5 stages of the cell cycle (determined by the shape of the DNA) a particular cell is currently in.",
        "unit": "stage",
        "key": "interphase-and-mitotic-stages",
        "discrete": true,
        "options": {
            "0": {
                "color": "#e9ebee",
                "name": "Interphase"
            },
            "1": {
                "color": "#c51b8a",
                "name": "Prophase"
            },
            "2": {
                "color": "#fed98e",
                "name": "Prometaphase"
            },
            "3": {
                "color": "#66c2a4",
                "name": "Metaphase"
            },
            "4": {
                "color": "#7f48f3",
                "name": "Anaphase"
            },
            "NaN": {
                "color": "#838383",
                "name": "Not determined"
            }
        }
    },
    {
        "key": "apical-proximity",
        "displayName": "Apical Proximity",
        "unit": "unitless",
        "description": "An intensity-derived image feature, defined as the optical intensity of a structure found in the top (apical) half of a roughly columnar cell as compared to the basal (bottom) half of this cell, scaled from -1 to 1. A cell in which all of the fluorescent intensity was in the top half would have an apical proximity of 1; whereas a structure that was evenly distributed between the apical and basal halves would have an apical proximity of 0",
        "tooltip": "An intensity-derived image feature, defined as the optical intensity of a structure found in the top (apical) half of a roughly columnar cell as compared to the basal (bottom) half of this cell, scaled from -1 to 1.",
        "discrete": false
    },
    {
        "key": "radial-proximity",
        "displayName": "Radial Proximity",
        "unit": "unitless",
        "description": "An intensity-derived image feature, defined as the optical intensity of a structure found in the more external shell of a roughly columnar cell (closer to the cell exterior) as compared to the more internal columnar core of the same cell (closer to the cell center), scaled from -1 to 1. A cell in which all of the fluorescence intensity was at the center of the cell would have a radial proximity of -1; whereas a structure that was at cell boundary would have a radial proximity of 1.",
        "tooltip": "An intensity-derived image feature, defined as the optical intensity of a structure found in the more external shell of a roughly columnar cell (closer to the cell exterior) as compared to the more internal columnar core of the same cell (closer to the cell center), scaled from -1 to 1. ",
        "discrete": false
    },
    {
        "key": "cell-line",
        "displayName": "Labeled Structure",
        "unit": "",
        "description": "Name of the cellular structure that has been fluorescently labeled in each cell line",
        "tooltip": "Name of the cellular structure that has been fluorescently labeled in each cell line",
        "discrete": true,
        "options": {
            "5": {
                "color": "#77207C",
                "name": "Matrix adhesions",
                "key": "Paxillin"
            },
            "7": {
                "color": "#FF96FF",
                "name": "Actin filaments",
                "key": "Alpha-actinin-1"
            },
            "10": {
                "color": "#FFFFB5",
                "name": "Endoplasmic reticulum",
                "key": "Sec61 beta"
            },
            "11": {
                "color": "#FFD184",
                "name": "Mitochondria",
                "key": "Tom20"
            },
            "12": {
                "color": "#6B4500",
                "name": "Microtubules",
                "key": "Alpha-tubulin"
            },
            "13": {
                "color": "#084AE7",
                "name": "Nuclear envelope",
                "key": "Lamin B1"
            },
            "14": {
                "color": "#A9D1E5",
                "name": "Nucleolus (Dense Fibrillar Component)",
                "key": "Fibrillarin"
            },
            "16": {
                "color": "#FFB1FF",
                "name": "Actin filaments",
                "key": "Beta-actin"
            },
            "17": {
                "color": "#A850E8",
                "name": "Desmosomes",
                "key": "Desmoplakin"
            },
            "22": {
                "color": "#AD952A",
                "name": "Lysosome",
                "key": "LAMP-1"
            },
            "23": {
                "color": "#A850D4",
                "name": "Tight junctions",
                "key": "Tight junction ZO-1"
            },
            "24": {
                "color": "#FF82FF",
                "name": "Actomyosin bundles",
                "key": "Non-muscle myosin heavy chain IIB"
            },
            "25": {
                "color": "#B7952A",
                "name": "Golgi",
                "key": "Sialyltransferase 1"
            },
            "32": {
                "color": "#9D7000",
                "name": "Centrosome",
                "key": "Centrin-2"
            },
            "33": {
                "color": "#FFD16E",
                "name": "Peroxisomes",
                "key": "Peroxisomal membrane protein PMP34"
            },
            "40": {
                "color": "#FFD150",
                "name": "Endosomes",
                "key": "Ras-related protein Rab-5A"
            },
            "53": {
                "color": "#A850C0",
                "name": "Gap junctions",
                "key": "Connexin-43"
            },
            "54": {
                "color": "#FFD2FF",
                "name": "Plasma membrane",
                "key": "CAAX domain of K-Ras"
            },
            "57": {
                "color": "#88D1E5",
                "name": "Nucleolus (Granular Component)",
                "key": "Nucleophosmin"
            },
            "58": {
                "color": "#CB1CCC",
                "name": "Adherens junctions",
                "key": "Beta-catenin"
            }
        }
    }
]

=== AllenInstitute/cell-feature-data/data/dataset-drug-0-1/feature_defs.json
[
  {
    "displayName": "Gene",
    "description": "Gene expressed by hiPSCs",
    "tooltip": "Gene expressed by hiPSCs",
    "unit": "gene",
    "key": "Gene",
    "discrete": true,
    "options": {
      "0": {
        "color": "#fed98e",
        "name": "TUBA1B"
      },
      "1": {
        "color": "#7f48f3",
        "name": "SEC61B"
      },
      "2": {
        "color": "#838383",
        "name": "ACTB"
      },
      "3": {
        "color": "#fed98e",
        "name": "ST6GAL1"
      },
      "4": {
        "color": "#fed98e",
        "name": "TJP1"
      },
      "5": {
        "color": "#fed98e",
        "name": "MYH10"
      },
      "6": {
        "color": "#fed98e",
        "name": "LAMP1"
      }
    }
  },
  {
    "displayName": "Objective",
    "description": "Magnification of the Objective used to image cells",
    "tooltip": "Magnification of the Objective used to image cells",
    "unit": "magnification",
    "key": "Objective",
    "discrete": true,
    "options": {
      "0": {
        "color": "#fed98e",
        "name": "100"
      }
    }
  },
  {
    "displayName": "Structure",
    "description": "Cellular structure that was GFP tagged in imaged cells",
    "tooltip": "Cellular structure that was GFP tagged in imaged cells",
    "unit": "structure",
    "key": "Structure",
    "discrete": true,
    "options": {
      "0": {
        "color": "#fed98e",
        "name": "Microtubules"
      },
      "1": {
        "color": "#7f48f3",
        "name": "Endoplasmic reticulum"
      },
      "2": {
        "color": "#838383",
        "name": "Actin filaments"
      },
      "3": {
        "color": "#fed98e",
        "name": "Golgi"
      },
      "4": {
        "color": "#fed98e",
        "name": "Tight junctions"
      },
      "5": {
        "color": "#fed98e",
        "name": "Actomyosin bundles"
      },
      "6": {
        "color": "#fed98e",
        "name": "Lysosome"
      }
    }
  },
  {
    "displayName": "Protein",
    "description": "Protein that is expressed with GFP tag in imaged cells",
    "tooltip": "Protein that is expressed with GFP tag in imaged cells",
    "unit": "protein",
    "key": "Protein_Name",
    "discrete": true,
    "options": {
      "0": {
        "color": "#fed98e",
        "name": "Alpha-tubulin"
      },
      "1": {
        "color": "#7f48f3",
        "name": "Sec61 beta"
      },
      "2": {
        "color": "#838383",
        "name": "Beta-actin"
      },
      "3": {
        "color": "#fed98e",
        "name": "Sialyltransferase 1"
      },
      "4": {
        "color": "#fed98e",
        "name": "Tight junction protein ZO-1"
      },
      "5": {
        "color": "#fed98e",
        "name": "Non-muscle myosin heavy chain IIB"
      },
      "6": {
        "color": "#fed98e",
        "name": "LAMP-1"
      }
    }
  },
  {
    "displayName": "Drug Treatment Group",
    "description": "Are the imaged cells treated with drug or vehicle",
    "tooltip": "Are the imaged cells treated with drug or vehicle",
    "unit": "drug-or-vehicle",
    "key": "treatment_group",
    "discrete": true,
    "options": {
      "0": {
        "color": "#fed98e",
        "name": "Drug"
      },
      "1": {
        "color": "#7f48f3",
        "name": "Vehicle"
      }
    }
  },
  {
    "displayName": "Drug Time Point",
    "description": "How many hours after drug addition was imaging done",
    "tooltip": "How many hours after drug addition was imaging done",
    "unit": "hours",
    "key": "time_point",
    "discrete": true,
    "options": {
      "0": {
        "color": "#fed98e",
        "name": "0.5"
      },
      "1": {
        "color": "#7f48f3",
        "name": "1"
      },
      "2": {
        "color": "#7f48f3",
        "name": "2"
      },
      "3": {
        "color": "#7f48f3",
        "name": "24"
      }
    }
  },
  {
    "displayName": "Drug Concentration",
    "description": "Concentration of Drug added to imaged cells, in units of \u00b5M",
    "tooltip": "Concentration of Drug added to imaged cells, in units of \u00b5M",
    "unit": "\u00b5M",
    "key": "concentration",
    "discrete": false
  }
]
