=== AllenInstitute/cell-feature-data/data-validation/schema/input-megaset.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "inputMegaset",
    "title": "Input Megaset `dataset.json`",
    "description": "File that describes a group of datasets (ie a 'Megaset'). Should be at the highest level, and the datasets nested in their own folders. This file needs to be named `dataset.json`",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "title": {
            "description": "Display name of the dataset or group",
            "type": "string"
        },
        "name": {
            "description": "Name of the dataset (no version number)",
            "type": "string"
        },
        "datasets": {
            "description": "subfolder names that point to each dataset in the group",
            "type": "array"
        },
        "publications": {
            "description": "Publications associated with the group",
            "type": "array",
            "items": {
                "properties": {
                    "title": {
                        "description": "Article title",
                        "type": "string"
                    },
                    "url": {
                        "description": "Article link",
                        "type": "string"
                    },
                    "citation": {
                        "description": "Article journal and date",
                        "type": "string"
                    }
                }
            }
        }
    },
    "required": [
        "title",
        "name"
    ]
}

=== AllenInstitute/cell-feature-data/dataset-cellsystems-2021/dataset.json
{
    "title": "Structural organization and gene expression in hiPSC-derived cardiomyocytes",
    "name": "cellsystems",
    "publications": [
        {
            "title": "",
            "url": "",
            "citation": ""
        },
        {
            "title": "",
            "url": "",
            "citation": ""
        }
    ],
    "datasets": [
        "fish/dataset.json",
        "live/dataset.json"
    ]
}
