=== AllenInstitute/cell-feature-data/data-validation/schema/input-dataset-info.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "input-dataset-info.schema.json",
    "title": "Input dataset info `dataset.json`",
    "description": "File containing the data needed to process a dataset. If single dataset, should be at the highest folder level. If one of many in a group of datasets, should be in a subfolder pointed to by the megaset JSON `datasets` array. Should be named `dataset.json`",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "title": {
            "description": "Display name of the dataset",
            "type": "string"
        },
        "name": {
            "description": "Name of the dataset (no version number)",
            "type": "string"
        },
        "version": {
            "description": "version year and number",
            "type": "string"
        },
        "description": {
            "description": "Description of the dataset",
            "type": "string"
        },
        "image": {
            "description": "relative path to the dataset card image file",
            "type": "string"
        },
        "link": {
            "description": "Link to website displaying the dataset",
            "type": "string"
        },
        "userData": {
            "description": "Optional display data",
            "type": "object"
        },
        "production": {
            "description": "Whether this dataset should only be shown in production",
            "type": "boolean"
        },
        "featuresDataPath": {
            "description": "url to the per cell data json",
            "type": "string"
        },
        "featureDefsPath": {
            "description": "path to the feature def collection",
            "type": "string"
        },
        "viewerSettingsPath": {
            "description": "path to image per-channel settings for the 3d viewer",
            "type": "string"
        },
        "albumPath": {
            "description": "collection name of the album data",
            "type": "string"
        },
        "thumbnailRoot": {
            "description": "Root url for thumbnail images",
            "type": "string"
        },
        "downloadRoot": {
            "description": "Root url for downloading cell data",
            "type": "string"
        },
        "volumeViewerDataRoot": {
            "description": "Root url for 3d images",
            "type": "string"
        },
        "xAxis": {
            "description": "Settings for the x axis",
            "type": "object",
            "$ref": "sub-schema/selection-setting.schema.json"
        },
        "yAxis": {
            "description": "Settings for the y axis",
            "type": "object",
            "$ref": "sub-schema/selection-setting.schema.json"
        },
        "colorBy": {
            "description": "Settings for the color by menu",
            "type": "object",
            "$ref": "sub-schema/selection-setting.schema.json"
        },
        "groupBy": {
            "description": "Settings for the grouping menu",
            "type": "object",
            "$ref": "sub-schema/selection-setting.schema.json"
        },
        "featuresDisplayOrder": {
            "description": "Ordered array of feature keys for display on front end",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "featuresDataOrder": {
            "description": "Ordered array of feature keys for packing and unpacking data",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "title",
        "version",
        "name",
        "image",
        "description",
        "featuresDataPath",
        "viewerSettingsPath",
        "albumPath",
        "thumbnailRoot",
        "downloadRoot",
        "volumeViewerDataRoot",
        "xAxis",
        "yAxis",
        "groupBy",
        "colorBy",
        "featuresDisplayOrder",
        "featuresDataOrder"
    ]
}

=== AllenInstitute/cell-feature-data/data/dataset-variance-resub-2022/main/dataset.json
{
  "title": "WTC-11 hiPSC Single-Cell Image Dataset",
  "version": "1",
  "name": "variance",
  "image": "",
  "description": "This is the full dataset described in the paper: Integrated intracellular organization and its variations in human iPS cells.",
  "userData": {
    "isNew": true,
    "inReview": false,
    "totalCells": 215081,
    "totalFOVs": 18000,
    "totalTaggedStructures": 25
  },
  "featureDefsPath": "feature_defs.json",
  "featuresDataPath": "cell_feature_analysis.json",
  "viewerSettingsPath": "images.json",
  "albumPath": "albums",
  "thumbnailRoot": "https://s3-us-west-2.amazonaws.com/bisque.allencell.org/v2.0.0/Cell-Viewer_Thumbnails",
  "downloadRoot": "https://files.allencell.org/api/2.0/file/download?collection=cellviewer-2-0",
  "volumeViewerDataRoot": "https://s3-us-west-2.amazonaws.com/bisque.allencell.org/v2.0.0/Cell-Viewer_Thumbnails",
  "xAxis": {
    "default": "cell-volume",
    "exclude": ["cell-line"]
  },
  "yAxis": {
    "default": "dna-volume",
    "exclude": ["cell-line"]
  },
  "colorBy": {
    "default": "cell-line"
  },
  "groupBy": {
    "default": "cell-line"
  },
  "featuresDisplayOrder": [
    "cell-line",
    "cell-height",
    "cell-volume",
    "cell-surface-area",
    "dna-height",
    "dna-volume",
    "dna-surface-area",
    "intracellular-structure-volume",
    "anaphase-segmentation-complete",
    "interphase-or-mitosis",
    "interphase-and-mitotic-stages",
    "shape-mode-1",
    "shape-mode-2",
    "shape-mode-3",
    "shape-mode-4",
    "shape-mode-5",
    "shape-mode-6",
    "shape-mode-7",
    "shape-mode-8",
    "outlier",
    "baseline",
    "sphere",
    "edge"
  ],
  "featuresDataOrder": [
    "cell-height",
    "cell-volume",
    "cell-surface-area",
    "dna-height",
    "dna-volume",
    "dna-surface-area",
    "intracellular-structure-volume",
    "anaphase-segmentation-complete",
    "interphase-or-mitosis",
    "interphase-and-mitotic-stages",
    "shape-mode-1",
    "shape-mode-2",
    "shape-mode-3",
    "shape-mode-4",
    "shape-mode-5",
    "shape-mode-6",
    "shape-mode-7",
    "shape-mode-8",
    "outlier",
    "baseline",
    "sphere",
    "edge",
    "angle",
    "cell-line"
  ]
}

=== AllenInstitute/cell-feature-data/data/dataset-variance-resub-2022/i1m1/dataset.json
{
  "title": "Interphase (i1) and prophase (m1) shape-matched cells",
  "version": "1",
  "name": "variance_i1m1",
  "image": "",
  "description": "Dataset of shape matched interphase and prophase cells.",
  "userData": {
    "isNew": true,
    "inReview": false,
    "totalCells": 4170,
    "totalFOVs": 0,
    "totalTaggedStructures": 25
  },
  "featureDefsPath": "feature_defs.json",
  "featuresDataPath": "cell_feature_analysis.json",
  "viewerSettingsPath": "images.json",
  "albumPath": "albums",
  "thumbnailRoot": "https://s3-us-west-2.amazonaws.com/bisque.allencell.org/v2.0.0/Cell-Viewer_Thumbnails",
  "downloadRoot": "https://files.allencell.org/api/2.0/file/download?collection=cellviewer-2-0",
  "volumeViewerDataRoot": "https://s3-us-west-2.amazonaws.com/bisque.allencell.org/v2.0.0/Cell-Viewer_Thumbnails",
  "xAxis": {
    "default": "cell-volume",
    "exclude": ["cell-line"]
  },
  "yAxis": {
    "default": "dna-volume",
    "exclude": ["cell-line"]
  },
  "colorBy": {
    "default": "cell-line"
  },
  "groupBy": {
    "default": "cell-line"
  },
  "featuresDisplayOrder": [],
  "featuresDataOrder": [
    "cell-height",
    "cell-volume",
    "cell-surface-area",
    "dna-height",
    "dna-volume",
    "dna-surface-area",
    "intracellular-structure-volume",
    "anaphase-segmentation-complete",
    "interphase-or-mitosis",
    "interphase-and-mitotic-stages",
    "shape-mode-1",
    "shape-mode-2",
    "shape-mode-3",
    "shape-mode-4",
    "shape-mode-5",
    "shape-mode-6",
    "shape-mode-7",
    "shape-mode-8",
    "angle",
    "type",
    "neigh",
    "lda",
    "cell-line"
  ]
}

=== AllenInstitute/cell-feature-data/data/dataset-variance-resub-2022/edges/dataset.json
{
  "title": "Non-edge and edge shape-matched cells",
  "version": "1",
  "name": "variance_edges",
  "image": "",
  "description": "This is shape-matched dataset of edge cells described in the paper: Integrated intracellular organization and its variations in human iPS cells.",
  "userData": {
    "isNew": true,
    "inReview": false,
    "totalCells": 9648,
    "totalFOVs": 0,
    "totalTaggedStructures": 25
  },
  "featureDefsPath": "feature_defs.json",
  "featuresDataPath": "cell_feature_analysis.json",
  "viewerSettingsPath": "images.json",
  "albumPath": "albums",
  "thumbnailRoot": "https://s3-us-west-2.amazonaws.com/bisque.allencell.org/v2.0.0/Cell-Viewer_Thumbnails",
  "downloadRoot": "https://files.allencell.org/api/2.0/file/download?collection=cellviewer-2-0",
  "volumeViewerDataRoot": "https://s3-us-west-2.amazonaws.com/bisque.allencell.org/v2.0.0/Cell-Viewer_Thumbnails",
  "xAxis": {
    "default": "cell-volume",
    "exclude": ["cell-line"]
  },
  "yAxis": {
    "default": "dna-volume",
    "exclude": ["cell-line"]
  },
  "colorBy": {
    "default": "cell-line"
  },
  "groupBy": {
    "default": "cell-line"
  },
  "featuresDisplayOrder": [],
  "featuresDataOrder": [
    "cell-height",
    "cell-volume",
    "cell-surface-area",
    "dna-height",
    "dna-volume",
    "dna-surface-area",
    "intracellular-structure-volume",
    "anaphase-segmentation-complete",
    "interphase-or-mitosis",
    "interphase-and-mitotic-stages",
    "shape-mode-1",
    "shape-mode-2",
    "shape-mode-3",
    "shape-mode-4",
    "shape-mode-5",
    "shape-mode-6",
    "shape-mode-7",
    "shape-mode-8",
    "angle",
    "type",
    "neigh",
    "lda",
    "cell-line"
  ]
}

=== AllenInstitute/cell-feature-data/data/dataset-cellsystems-2021/live/dataset.json
{
  "title": "hiPSC-derived Cardiomyocyte Live Dataset",
  "version": "2021.1",
  "name": "cellsystems_live",
  "image": "thumb_livecardio.png",
  "description": "This dataset is one of the two datasets accompanying the Cell Systems manuscript. This one presents live-captured FOVs of cardiomyocytes at different timepoints. For more information please click on the link below to access the manuscript.",
  "userData": {
    "isNew": true,
    "inReview": false,
    "totalCells": 18045,
    "totalFOVs": 1696,
    "totalTaggedStructures": 1
  },
  "featureDefsPath": "feature_defs.json",
  "featuresDataPath": "cell_feature_analysis_live.json",
  "viewerSettingsPath": "images.json",
  "albumPath": "albums",
  "thumbnailRoot": "https://s3-us-west-2.amazonaws.com/bisque.allencell.org/cellsystems-2021-live.1/Cell-Viewer_Thumbnails",
  "downloadRoot": "https://files.allencell.org/api/2.0/file/download?collection=cellsystems-2021-live_1",
  "volumeViewerDataRoot": "https://s3-us-west-2.amazonaws.com/bisque.allencell.org/cellsystems-2021-live.1/Cell-Viewer_Thumbnails",
  "xAxis": {
    "default": "expert-score"
  },
  "yAxis": {
    "default": "cos"
  },
  "colorBy": {
    "default": "cell-age"
  },
  "groupBy": {
    "default": "cell-age"
  },
  "featuresDisplayOrder": [
    "cell-age",
    "expert-score",
    "cos",
    "area-zdisk",
    "area-orgpuncta",
    "area-disorgpuncta",
    "area-fibers",
    "area-diffuse",
    "area-background",
    "max-cov",
    "peak-height",
    "peak-distance",
    "protein-density",
    "cell-area",
    "cell-aspect",
    "diff-exp",
    "plate-barcode",
    "well"
  ],
  "featuresDataOrder": [
    "cell-age",
    "expert-score",
    "cos",
    "area-zdisk",
    "area-orgpuncta",
    "area-disorgpuncta",
    "area-fibers",
    "area-diffuse",
    "area-background",
    "max-cov",
    "peak-height",
    "peak-distance",
    "protein-density",
    "cell-area",
    "cell-aspect",
    "diff-exp",
    "plate-barcode",
    "well"
  ]
}
