=== AllenInstitute/cell-feature-data/data-validation/schema/megaset-card.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "megaset-card.schema.json",
    "title": "Megaset Card",
    "description": "Data needed to render a megaset card",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "datasets": {
            "type": "array",
            "items": {
                "$ref": "sub-schema/dataset-card.schema.json"
            }
        },
        "dateCreated": {
            "description": "Month Day, Year",
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "production": {
            "type": "boolean"
        },
        "title": {
            "type": "string"
        },
        "publications": {
            "description": "Publications associated with the group",
            "type": "array",
            "items": {
                "$ref": "sub-schema/publication.schema.json"
            }
        }
    }
}

=== AllenInstitute/cell-feature-data/dataset-variance-resub-2022/dataset.json
{
    "title": "hiPSC Single-Cell Image Dataset",
    "name": "In revision",
    "dateCreated": "Jul 13, 2022",
    "publications": [
        {
            "title": "Integrated intracellular organization and its variations in human iPS cells",
            "url": "",
            "citation": "In revision"
        }
    ],
    "datasets": [
        "main"
    ]
}

=== AllenInstitute/cell-feature-data/data/dataset-variance-resub-2022/dataset.json
{
    "title": "WTC-11 hiPSC Single-Cell Image Dataset v1",
    "name": "variance_nature",
    "dateCreated": "Jul 13, 2022",
    "publications": [
        {
            "title": "Integrated intracellular organization and its variations in human iPS cells",
            "url": "https://www.nature.com/articles/s41586-022-05563-7",
            "citation": "Nature, January 2023"
        }
    ],
    "datasets": [
        "main",
        "edges",
        "i1m1",
        "i2m2"
    ]
}
